spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

